# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all ava123ilable plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    # upload_to_play_store(track: 'internal', apk: 'dummy_app_v2.apk', release_status:'draft')
    upload_to_play_store(track: 'internal', apk: 'app/build/outputs/apk/release/app-release.aab', release_status:'draft')
  end

  desc "Promote Internal to Alpha"
  lane :promote_internal_to_alpha do
    upload_to_play_store(track: 'internal', track_promote_to: 'alpha', release_status:'draft')
  end

  desc "Promote Alpha to Beta"
  lane :promote_alpha_to_beta do
    upload_to_play_store(track: 'alpha', track_promote_to: 'beta', release_status:'draft')
  end

  desc "Promote Beta to Production"
  lane :promote_beta_to_production do
    upload_to_play_store(track: 'beta', track_promote_to: 'production', release_status:'draft')
  end

  desc "Check key"
  lane :validateJSON do
  validate_play_store_json_key(json_key: '~/google_play_api_key.json')
  end
end
